### ISSUE TITLE
Feature request: Automatically setup r13/RTOC

### ISSUE THREAD

**Issue by phire** [Cuyler36/Ghidra-GameCube-Loader#2]
I don't know if it's possible for a loader to do this, but it would would improve the experience, especially for new users.

**Comment by Cuyler36** [comment]
I looked into doing this and it seems feasible, however the database has to have been analyzed for it to work properly. Since that won't happen until the loader has completed its function, it's probably out of this project's scope.

Unless there's a way to hook a callback up to auto analysis completion, a script or plugin would need to be made separately.

**Comment by RenaKunisaki** [comment]
I don't know if it has to do with this script, but I've got ghidra into some state where it refuses to set r13 beyond a certain address, and just spits out lots of `iVar4 = *(&DAT_ffff979c + unaff_r13);` and such. Have you seen this before?

**Comment by Cuyler36** [comment]
Closed by https://github.com/Cuyler36/Ghidra-GameCube-Loader/commit/803338fc8b991f96a3e011d7af668706eedf469e
