### ISSUE TITLE
Incorrect starting addresses for functions in rel files

### ISSUE THREAD

**Issue by Zephiles** [Cuyler36/Ghidra-GameCube-Loader#22]
This is an issue that I'm getting with a Japanese demo version of Paper Mario: The Thousand-Year Door. With the current build, when the dol and rel files are all loaded at once, a lot of starting addresses for functions in rel files are 4 to 8 bytes ahead of where they should be. So for instance, the first rel file in the list is **aaa.rel**, and the address it currently has listed for the **_epilog** is at `8041e90c`. This address is 8 bytes past where the start of this function actually is.

Also, i still have a project of this from a previous version, which properly has the address set to `8041e904`, so it was working correctly at some point before.

**Comment by Cuyler36** [comment]
Since relocatable modules don't have absolute defined addresses in memory, the loader aligns each one to 32-bytes. You can specify the address of each module by hand using an option on project creation if you'd like to set the file's address to what it is in a RAM dump. This is a change I made to prevent collisions in a previous commit.

**Comment by Zephiles** [comment]
The alignment thing is fine, but the problem is that its not correctly setting the start of the function. As in, its skipping the first or second instruction in the function.

**Comment by Cuyler36** [comment]
Ah okay. I haven't encountered that behavior before. I think I have that demo so I'll take a look at the symbol map and see if I can figure out what's going on.
