### ISSUE TITLE
Unaligned symbols?

### ISSUE THREAD

**Issue by magcius** [Cuyler36/Ghidra-GameCube-Loader#28]
![image](https://user-images.githubusercontent.com/40890/71634216-06c4b200-2bcf-11ea-8432-8bb162c9f366.png)

The game is trying to call `Set(&param_1->mSph1, d_a_ep::sph_src)`, but for some reason, Ghidra loaded it at 0x8041d4e5 instead of where it should be placed, 0x8041d4e4. I've confirmed that it's an issue with the data's placement -- if I interpret the struct at 0x4e5, the data looks sensible.

This is Wind Waker. Note that this symbol comes from a REL.

**Comment by Cuyler36** [comment]
There's probably an issue with data alignment being read from the symbol map. I'll check it out in a few days when I'm back from holiday.

**Comment by Zephiles** [comment]
I can confirm that this is happening in other games as well, such as Paper Mario: The Thousand-Year Door. With the Japanese demo disc, I'm checking the following entry in `gor.plf.MAP`:

`000164f4 000030 000164f4  4 goods_list 	gor_01.o `

But when this is imported into Ghidra, the end result is this:
![Untitled](https://user-images.githubusercontent.com/24236945/80893416-a6866f80-8c97-11ea-9e73-576698404fb9.png)

I would imagine it's because the `rodata` section is not aligned to 4 bytes:
```
Memory map:
                   Starting Size     File
                   address           Offset
            .text  00000000 00011ab8 00000040
           .ctors  00000000 00000004 00011af8
           .dtors  00000000 00000004 00011afc
          .rodata  00000000 0000bb65 00011b00
            .data  00000000 0004a014 0001d668
             .bss  00000000 00000200 00067680
   .debug_srcinfo           000000 00000000
   .debug_sfnames           000000 00000000
           .debug           000000 00000000
            .line           000000 00000000
