### ISSUE TITLE
Unfixed overlapping + Unresolved function calls

### ISSUE THREAD

**Issue by Zephiles** [Cuyler36/Ghidra-GameCube-Loader#5]
This is an issue I'm seeing with Twilight Princess. While the most recent update fixed these issues for TTYD, it seemed to have no effect for Twilight Princess.

![Overlapping](https://i.imgur.com/1blqUec.png)

In terms of the function calls, most of the appear to work fine until somewhere around the time where the rel file in the picture was added.

My only guess is that these issues are occurring because the map files for Twilight Princess are in a much different format than a lot of others. They appear to be more like Dolphin map files, in which there is no Memory map section. This applies to both the map file for the dol (frameworkF.map) and all of the other map files for the rel files.

**Comment by Cuyler36** [comment]
When you say the function calls are unresolved do you mean the symbol? Or is it not relocating the address so the function call is malformed?

**Comment by Zephiles** [comment]
It should be the latter, as all of the rel files earlier in the list always call **ModuleConstructorsX** and **ModuleProlog**, but all of the ones at this point and after are unresolved.

**Comment by Cuyler36** [comment]
So this issue is caused by the symbol maps in Twilight Princess missing the Memory Map Info section at the bottom of the symbol map files for rels. Without it, the Symbol Loader can't get the correct offset into the rel file where the symbols should be placed for each section, which causes them to use relAddress+0 as the beginning offset.
The only way I can come up with for a fix is by using the sections in the rel's header instead, but it's not always 1:1 with the symbol map. I'll see what I can do.
